### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by kaaax0815** [Infinixius/spud#1]
Is Inventory being worked on?

Maybe a simple editor to add e.g food or edit quantity would be a great start

**Comment by Infinixius** [comment]
hey! kinda forgot this project existed lol

i went ahead and pushed a new version that implements a basic inventory editor! let me know if you have any ideas or improvements!
![image](https://user-images.githubusercontent.com/68125679/135178568-e55654ff-5491-46aa-a0fb-f44cabc11a8a.png)
![image](https://user-images.githubusercontent.com/68125679/135178576-f27bff6b-abc1-4071-aa43-4f68eea37f31.png)

**Comment by kaaax0815** [comment]
Thanks. I am currently working on a own version with a interactive inventory
