### ISSUE TITLE
Does not work with SPD v1.1

### ISSUE THREAD

**Issue by EmanueleCiriachi** [Infinixius/spud#2]
Any chance this could be updated?

**Comment by Infinixius** [comment]
it seems like newer versions use a save file format other than JSON, which is what older versions and the save editor use.

the editor then gets angry that there's no commas, and fails. i'll look into it later, thanks for letting me know! 👍 

![image](https://user-images.githubusercontent.com/68125679/147417653-0f0825d1-e2e8-49a5-b30b-a519e31e5c72.png)

**Comment by EmanueleCiriachi** [comment]
Cheers, thanks for the quick reply.

Do you happen to know what compression format is used for the save files? I unzipped game.dat, modified it and re-compressed it, but when I put the file back the game is not recognized.

**Comment by Infinixius** [comment]
make sure you're using [gzip](https://en.wikipedia.org/wiki/Gzip) to zip the save files, and **gunzip** to unzip them.

as noted on the website, re-zipping up the game.dat file after modifying it causes the game to not read it properly. leaving just the JSON save file with the same name in the save directory should work completely fine.

**Comment by Infinixius** [comment]
the [editor](https://infinixius.github.io/spud/) should work now! i pushed an update that uses the game's new [HJSON](https://hjson.github.io/) format fixing the issue.

let me know if it works or breaks again, tysm!
