### ISSUE TITLE
The site is not working. How to use this utility now?

### ISSUE THREAD

**Issue by K0rz1ch** [Infinixius/spud#3]
Hello. I used your tool a couple of months ago and it worked. But recently I decided to try to run it again, but it doesn’t work anymore. The site unfortunately no longer works. When I try to run the source code in Visual Studio Code, the browser says JavaScript is not working. How to solve this problem?

**Comment by Infinixius** [comment]
i recently switched my server host from GitHub pages to my own personal server, and the url changed in the process. are you trying to use [https://infinixi.us/spud/](https://infinixi.us/spud/) or [https://infinixius.github.io/spud](https://infinixius.github.io/spud)?

as for running the source code yourself in Visual Studio Code, opening the `index.html` file in your browser won't work:
![image](https://user-images.githubusercontent.com/68125679/173192549-f284f74e-e83c-48f0-b038-9f5c5d6c0354.png)
you need setup a basic http server yourself and host the website from there. there is a very useful [vscode extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) that will do this for you.
